name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello, thanks for creating an issue and contributing to our project! ~WSL(http://wsl.iiitb.ac.in/)'
        pr-message: 'Hello, thanks for creating a PR and contributing to our project! ~WSL(http://wsl.iiitb.ac.in/)'
